---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repository-${name}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: ${type}
type: Opaque
stringData:
%{~ if type == "repository" }
  type: git
%{~ endif }
  url: ${url}
%{~ if username != null }
  username: ${username}
%{~ endif }
%{~ if password != null }
  password: ${password}
%{~ endif }
%{~ if ssh_private_key != null }
  ssh-private-key: |
    ${replace(replace(ssh_private_key, "\r\n", "\n"), "\n", "\n    ")}
%{~ endif }
%{~ if secret != null }
  password: ${secret}
%{~ endif }
